//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Userregistration.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Userlog
    {
        public int UserID { get; set; }
        [Required (ErrorMessage="This Feild is required")]
        public string Username { get; set; }
         [Required(ErrorMessage = "This Feild is required")]
        [DataType(DataType.Password)]
        public string Passwoord { get; set; }
        [DataType(DataType.Password)]
         [DisplayName("Confirm Passwoord")]
         [Compare("Passwoord", ErrorMessage = "The password and confirmation password do not match.")]
         
        public string confirmpassword { get; set; }
        public bool IsAdmin { get; set; }
    }
}
